orbs:
  node: circleci/node@4.2.1
  heroku: circleci/heroku@1.2.6 # Use the Heroku orb in your config

version: 2.1

jobs:
  build:
      docker:
        - image: docker
      steps:
        - setup_remote_docker:
            docker_layer_caching: true
        - run: docker image ls
        - run: docker volume ls
        - run: docker run --mount source=datastore,destination=/mnt/volume debian:bullseye-slim dd if=/dev/zero of=/mnt/volume/zero bs=32M count=32
        - run: docker volume ls
        - run: echo hello Miranda
        - store_test_results
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  app-tests:
    jobs:
      - build
  deploy:
    jobs:
      - build
      - deploy