orbs:
  node: circleci/node@4.2.1
  heroku: circleci/heroku@1.2.6 # Use the Heroku orb in your config

# version: 2.1

jobs:
  build:
      docker:
        - image: docker
      steps:
        - setup_remote_docker:
            docker_layer_caching: true
        - run: docker image ls
        - run: docker volume ls
        - run: docker run --mount source=datastore,destination=/mnt/volume debian:bullseye-slim dd if=/dev/zero of=/mnt/volume/zero bs=32M count=32
        - run: docker volume ls
        - run: echo hello Miranda
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  app-tests:
    jobs:
      - build
  heroku_deploy:
    jobs:
      - build
      - deploy
          # requires:
          #   - build # only run deploy-via-git job if the build job has completed
          # filters:
          #   branches:
          #     only: master # only run deploy-via-git job on master branch
