version: '2.1'
orbs:
  heroku: circleci/heroku@1.2.6
  node: circleci/node@4.7
workflows:
  test-and-deploy:
    jobs:
      - node/test
      - heroku/deploy-via-git:
          filters:
            branches:
              only:
                - master
          requires:
            - node/test